Release 2.1.6

diff --git a/.github/workflows/build-matterbridge-plugin.yml b/.github/workflows/build-matterbridge-plugin.yml
--- a/.github/workflows/build-matterbridge-plugin.yml
+++ b/.github/workflows/build-matterbridge-plugin.yml
@@ -13,7 +13,8 @@ jobs:
         os: [ubuntu-latest, windows-latest, macos-latest]
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Use Node.js ${{ matrix.node-version }} 
         uses: actions/setup-node@v4
@@ -21,7 +22,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install matterbridge
-        run: npm -g install matterbridge
+        run: npm install -g matterbridge
 
       - name: Install dependencies
         run: npm install
@@ -31,4 +32,15 @@ jobs:
 
       - name: Build the project
         run: npm run build
+
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          npm uninstall matterbridge
+          npm list --outdated
+          npm audit || true  # ignore failures
+          npm audit fix || true
+          npm list --outdated
+          npm install -g matterbridge
+          npm install
+          npm run build
 
